// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiLingo.Infra.Persistence;

namespace MultiLingo.Infra.Migrations
{
    [DbContext(typeof(MultiLingoContext))]
    partial class MultiLingoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiLingo.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdTurma");

                    b.Property<bool>("IsDeletado");

                    b.Property<string>("Matricula")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("IdAluno");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("MultiLingo.Domain.Entities.AlunoTurma", b =>
                {
                    b.Property<Guid>("IdAluno");

                    b.Property<Guid>("IdTurma");

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataInsercao");

                    b.Property<DateTime?>("DataRemovido");

                    b.Property<Guid>("IdAlunoTurma");

                    b.HasKey("IdAluno", "IdTurma");

                    b.HasAlternateKey("IdAlunoTurma");

                    b.HasIndex("IdTurma");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("MultiLingo.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("IdTurma")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeletado");

                    b.Property<string>("Nome");

                    b.HasKey("IdTurma");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("MultiLingo.Domain.Entities.AlunoTurma", b =>
                {
                    b.HasOne("MultiLingo.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Turmas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MultiLingo.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
